package server;

import java.io.Serializable;
import java.util.Date;


/**
 * 
 * @author rifl
 * Message Class provide transport message objects for jChatApp 
 * Messages Types:
 * 1 - chatMessage
 * 2 - userAdd
 * 3 - userRemove
 * 4 - changeUsername
 * 5 - join Conversation
 * 6 - leave conversation
 * 9 - disconnect
 * ->> Add needed commands here and add method to MessageHandler
	 */
public class Message implements Serializable {

	/**
	 * Generated by Eclipse from implementing serialazeble
	 */
	private static final long serialVersionUID = 1223417195930483671L;

	private MessageType messageType;
	private String conversationName;
	private String senderID;
	private String content;
	private int messageID;
	private Date timestamp;
	
	// Constructor
	public Message(MessageType messageType, String content, String conversationName, String senderID){
		this.messageType = messageType;
		this.content = content;
		this.timestamp = new Date();
		this.conversationName = conversationName;
		this.senderID = senderID;
		this.messageID = this.hashCode();
	}
	
	public MessageType getMessageType() {
		return messageType;
	}
	
	public String getContent() {
		return content;
	}
	
	public String getConversationName() {
		return conversationName;
	}
	
	public String getSenderName() {
		return senderID;
	}
	
	public Date getTimestamp() {
		return timestamp;
	}
	
	public int getMessageID() {
		return messageID;
	}
	
	public String getChatMessage(){
		return timestamp.toString() + " [" + senderID + "]: "+content;
	}
	
}