package server;

import java.io.Serializable;
import java.util.Date;

/**
 * 
 * @author rifl
 * Message Class provide transport message objects for jChatApp 
 * Messages Types:
 * 1 - chatMessage
 * 2 - userAdd
 * 3 - userRemove
 * 4 - Create Conversation
 * 5 - Remove Conversation
 * 9 - disconnect
 * ->> Add needed commands here and add method to MessageHandler
	 */
public class Message implements Serializable {

	/**
	 * Generated by Eclipse from implementing resialazeble
	 */
	private static final long serialVersionUID = 1223417195930483671L;

	private int messageType;
	private String conversationName;
	private String senderID;
	private String content;
	private int messageID;
	private Date timestamp;
	
	// Constructor
	public Message(int i, String c, String cid, String sid){
		messageType = i;
		content = c;
		timestamp = new Date();
		conversationName = cid;
		senderID = sid;
		messageID = this.hashCode();
	}
	
	public int getMessageType() {
		return messageType;
	}
	
	public String getContent() {
		return content;
	}
	
	public String getConversationName() {
		return conversationName;
	}
	
	public String getSenderName() {
		return senderID;
	}
	
	public Date getTimestampD() {
		return timestamp;
	}
	
	public int getMessageID() {
		return messageID;
	}
	
	public String getChatMessage(){
		return timestamp.toString() + " " + senderID + ": "+content;
	}
	
}